[project]
name = "un-budget-explorer"
version = "0.1.0"
description = "UN Budget Explorer"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-docx>=1.1.2",
    "ipykernel>=7.1.0",
    "pandas>=2.3.3",
]
